//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERS_VIEW
    {
        public int Customer_ID { get; set; }
        public string Customer_First_name { get; set; }
        public string Customer_Last_name { get; set; }
        public string Customer_Address { get; set; }
        public int No__of_Peoples { get; set; }
        public Nullable<long> Customer_Phone_No_s { get; set; }
        public string Customer_Email_Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
