//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employees_Contact_No_s = new HashSet<Employees_Contact_No_s>();
            this.Transactions = new HashSet<Transaction>();
            this.Employees_Contact_No_s1 = new HashSet<Employees_Contact_No_s>();
            this.Transactions1 = new HashSet<Transaction>();
        }
    
        public int Employee_ID { get; set; }
        public string Employee_First_Name { get; set; }
        public string Employee_Last_Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Employee_Department { get; set; }
        public string Employee_Address { get; set; }
        public Nullable<decimal> Employee_Salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees_Contact_No_s> Employees_Contact_No_s { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees_Contact_No_s> Employees_Contact_No_s1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions1 { get; set; }
    }
}
