//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES_VIEW
    {
        public int Employee_ID { get; set; }
        public string Employee_First_name { get; set; }
        public string Employee_Last_name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Employee_Department { get; set; }
        public string Employee_Address { get; set; }
        public Nullable<decimal> Employee_Salary { get; set; }
        public Nullable<long> Employee_Contact_No_s { get; set; }
    }
}
