//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Hotel_Management_SystemEntities : DbContext
    {
        public Hotel_Management_SystemEntities()
            : base("name=Hotel_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_s_Phone_No_s> Customer_s_Phone_No_s { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employees_Contact_No_s> Employees_Contact_No_s { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<CUSTOMERS_VIEW> CUSTOMERS_VIEWs { get; set; }
        public virtual DbSet<EMPLOYEES_VIEW> EMPLOYEES_VIEWs { get; set; }
        public virtual DbSet<RESERVATIONS_VIEW> RESERVATIONS_VIEWs { get; set; }
        public virtual DbSet<TRANSACTIONS_VIEW> TRANSACTIONS_VIEWs { get; set; }
    
        public virtual int sp_IOS(Nullable<int> transaction_ID, Nullable<int> customer_ID, Nullable<System.DateTime> date_In, Nullable<System.DateTime> date_Out)
        {
            var transaction_IDParameter = transaction_ID.HasValue ?
                new ObjectParameter("Transaction_ID", transaction_ID) :
                new ObjectParameter("Transaction_ID", typeof(int));
    
            var customer_IDParameter = customer_ID.HasValue ?
                new ObjectParameter("Customer_ID", customer_ID) :
                new ObjectParameter("Customer_ID", typeof(int));
    
            var date_InParameter = date_In.HasValue ?
                new ObjectParameter("Date_In", date_In) :
                new ObjectParameter("Date_In", typeof(System.DateTime));
    
            var date_OutParameter = date_Out.HasValue ?
                new ObjectParameter("Date_Out", date_Out) :
                new ObjectParameter("Date_Out", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_IOS", transaction_IDParameter, customer_IDParameter, date_InParameter, date_OutParameter);
        }
    }
}
