//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Transaction_ID { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public long No__of_Days_Stay { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
