//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int RID { get; set; }
        public Nullable<int> Customer_ID_Name { get; set; }
        public string Review_Details { get; set; }
        public Nullable<System.DateTime> Review_Date { get; set; }
        public string Customer_Email_Address { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
    }
}
