//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Room_No { get; set; }
        public string Room_Category { get; set; }
        public Nullable<long> Rent { get; set; }
        public Nullable<int> Reservation_ID { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Reservation Reservation1 { get; set; }
    }
}
