//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONS_VIEW
    {
        public int Transaction_ID { get; set; }
        public string Transaction_Name { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<long> No__of_Days_Stay { get; set; }
    }
}
